/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/j2ZsUSwWzZ1
 */
import { CardTitle, CardDescription, CardContent, Card } from "@/components/ui/card"

export function Nutrition() {
  return (
    <div className="grid grid-cols-[3fr_1fr] gap-4 h-screen p-4">
      <div className="overflow-auto">
        <h1 className="text-2xl font-bold mb-4">Food List</h1>
        <div className="grid gap-4">
          <Card>
            <CardContent className="flex items-center justify-between">
              <div>
                <CardTitle>Chicken Breast</CardTitle>
                <CardDescription>Serving Size: 100g</CardDescription>
              </div>
              <div className="text-lg font-bold">31g Protein</div>
            </CardContent>
          </Card>
          <Card>
            <CardContent className="flex items-center justify-between">
              <div>
                <CardTitle>Salmon</CardTitle>
                <CardDescription>Serving Size: 100g</CardDescription>
              </div>
              <div className="text-lg font-bold">20g Protein</div>
            </CardContent>
          </Card>
          <Card>
            <CardContent className="flex items-center justify-between">
              <div>
                <CardTitle>Almonds</CardTitle>
                <CardDescription>Serving Size: 100g</CardDescription>
              </div>
              <div className="text-lg font-bold">21g Protein</div>
            </CardContent>
          </Card>
          <Card>
            <CardContent className="flex items-center justify-between">
              <div>
                <CardTitle>Quinoa</CardTitle>
                <CardDescription>Serving Size: 100g</CardDescription>
              </div>
              <div className="text-lg font-bold">4.4g Protein</div>
            </CardContent>
          </Card>
        </div>
      </div>
      <div className="border-l pl-4">
        <h1 className="text-2xl font-bold mb-4">Selected Foods</h1>
        <div className="grid gap-4 mb-4">
          <Card>
            <CardContent className="flex items-center justify-between">
              <div>
                <CardTitle>Chicken Breast</CardTitle>
                <CardDescription>Serving Size: 100g</CardDescription>
              </div>
              <div className="text-lg font-bold">31g Protein</div>
            </CardContent>
          </Card>
          <Card>
            <CardContent className="flex items-center justify-between">
              <div>
                <CardTitle>Almonds</CardTitle>
                <CardDescription>Serving Size: 100g</CardDescription>
              </div>
              <div className="text-lg font-bold">21g Protein</div>
            </CardContent>
          </Card>
        </div>
        <div className="border-t pt-4">
          <h2 className="text-xl font-bold mb-2">Total Protein</h2>
          <p className="text-lg">52g</p>
        </div>
      </div>
    </div>
  )
}
